parameters:
    pgsql_test:
        driver: pgsql
        host: db4free.net
        port: '3306'
        name: esoldb
        user: esoldb
        password: 4GwpEudP47s5qGD
    mysql_test:
        driver: mysql
        host: db4free.net
        port: '3306'
        name: esoldb
        user: esoldb
        password: 4GwpEudP47s5qGD
